version: '2'
services:
  tws:
    build: .
    ports:
      - "127.0.0.1:4003:4003"
      - "127.0.0.1:5901:5900"
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=Asia/Chongqing
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=1234 # CHANGEME
      - TWS_MAJOR_VRSN=974
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - TRADING_MODE=paper # either paper or live
      - TWSUSERID=fdemo # IB account
      - TWSPASSWORD=demouser # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - JAVA_PATH=
      - APP=GATEWAY
